name: Publish Docker
on: 
  workflow_dispatch:
jobs:
  pxc-operator-proxysql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vmatrixdev/percona-xtradb-cluster-operator
        tag: "1.5.0-proxysql"
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        dockerfile: "pxc-operator/Dockerfile.proxysql"
