name: Publish Docker
on: 
  workflow_dispatch:
jobs:
  pxc-operator-proxysql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download proxysql-admin
      run: "wget https://raw.githubusercontent.com/percona/proxysql-admin-tool/v2.0/proxysql-admin && chmod 775 proxysql-admin"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vmatrixdev/percona-xtradb-cluster-operator
        tags: "1.5.0-proxysql"
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        dockerfile: "pxc-operator/Dockerfile.proxysql"
  tkestack-gpu-manager:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: tkestack/gpu-manager
        ref: 19a87c5b12c4f41e4add16c0f5e426751af4b46a
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        version: "1.1.0-matrix"
        commit: "19a87c5b"
        base_img: "tkestack/vcuda:1.0.1"
      with:
        name: vmatrixdev/gpu-manager
        tags: "1.1.0-matrix"
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        dockerfile: "build/Dockerfile"
        workdir: "build"
        buildargs: "version,commit,base_img"
