name: Build judge-env-aio
on: ["push"]
jobs:
  judge-env-aio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vmatrixdev/judge-env-aio
        tags: "latest"
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        dockerfile: "judge-env-aio/Dockerfile"
