name: Build judge-env Docker Images
on: ["push"]
jobs:
  all-in-one:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: vmatrixdev/judge-env-aio
        tags: "latest"
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        dockerfile: "judge-env/all-in-one.Dockerfile"
  cpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: vmatrixdev/judge-env-cpp
        tags: "latest"
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        dockerfile: "judge-env/cpp.Dockerfile"
