# This is a basic workflow to help you get started with Actions

name: Docker Hub Retention

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "13 10 1 * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pull:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: docker pull
      run: |
        docker pull -a vmatrixdev/cert-manager-webhook-dnspod
        docker pull -a vmatrixdev/che-plugin-registry-offline
        docker pull -a vmatrixdev/canal-adapter
        docker pull -a vmatrixdev/es-smartcn
        docker pull -a vmatrixdev/percona-xtradb-cluster-operator
        docker pull -a vmatrixdev/canal-server
        docker pull -a vmatrixdev/koko
        docker pull -a vmatrixdev/lazykube
        docker pull -a vmatrixdev/pwm-webapp
        docker pull -a vmatrixdev/node-pm2
        docker pull -a vmatrixdev/nginx
        docker pull -a vmatrixdev/node
        docker pull -a vmatrixdev/xwiki
